import {StyleSheet} from 'react-native';
import {COLORS} from '@constants/colors';
import {FONTS} from '@constants/fonts';

export default StyleSheet.create({
  screen: {flex: 1, backgroundColor: COLORS.grayscale_0},
  content: {paddingHorizontal: 20, paddingTop: 40, paddingBottom: 32, gap: 20},
  heading: {gap: 6},
  title: {...FONTS.fs_22_bold, color: COLORS.grayscale_900},
  subtitle: {...FONTS.fs_14_regular, color: COLORS.grayscale_500},
  card: {
    borderWidth: 1,
    borderColor: COLORS.grayscale_200,
    borderRadius: 14,
    padding: 16,
    gap: 14,
  },
  cardTitle: {...FONTS.fs_16_semibold, color: COLORS.grayscale_800},
  divider: {height: 1, backgroundColor: COLORS.grayscale_200},
  field: {gap: 7},
  label: {...FONTS.fs_12_medium, color: COLORS.grayscale_700},
  inputBox: {
    height: 46,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: COLORS.grayscale_300,
    borderRadius: 10,
    backgroundColor: COLORS.grayscale_100,
  },
  input: {...FONTS.fs_14_regular, color: COLORS.grayscale_900, flex: 1, paddingVertical: 0},
  smallButton: {
    backgroundColor: COLORS.primary_orange,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 14,
  },
  smallButtonText: {...FONTS.fs_12_medium, color: COLORS.grayscale_0},
  helper: {...FONTS.fs_12_medium},
  error: {color: COLORS.semantic_red},
  success: {color: COLORS.semantic_green},
  choiceRow: {flexDirection: 'row', gap: 8},
  choice: {
    flex: 1,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.grayscale_300,
    borderRadius: 22,
  },
  choiceSelected: {borderColor: COLORS.primary_orange, backgroundColor: COLORS.primary_orange},
  choiceText: {...FONTS.fs_14_medium, color: COLORS.grayscale_600},
  choiceTextSelected: {color: COLORS.grayscale_0},
  languageGrid: {flexDirection: 'row', flexWrap: 'wrap', gap: 8},
  languageChoice: {
    width: '48%',
    flexGrow: 1,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.grayscale_300,
    borderRadius: 22,
  },
  allAgreementRow: {flexDirection: 'row', alignItems: 'center', gap: 8},
  allAgreementText: {...FONTS.fs_14_semibold, color: COLORS.grayscale_800},
  agreementRow: {flexDirection: 'row', alignItems: 'center', gap: 8},
  agreementLabel: {flex: 1},
  agreementText: {...FONTS.fs_12_medium, color: COLORS.grayscale_700},
  viewText: {...FONTS.fs_12_medium, color: COLORS.primary_orange},
  submitButton: {marginTop: 4},
});
