export const WEB_ROUTES = {
  HOME: '/',
  COMMUNITY: '/community',
  COMMUNITY_DETAIL: postId => `/community/posts/${postId}`,
  COMMUNITY_STAFF_DETAIL: id => `/community/staff/${id}`,
  COMMUNITY_WRITE: '/community/write',
  CONTENTS: '/contents',
  EMPLOY: '/employ',
  EMPLOY_DETAIL: id => `/employ/${id}`,
  EMPLOY_MAP: '/employ/map',
  EMPLOY_SEARCH: '/employ/search',
  EMPLOY_SEARCH_RESULT: '/employ/search/results',
  GUESTHOUSE_DETAIL: id => `/guesthouses/${id}`,
  GUESTHOUSE_LOCATION: id => `/guesthouses/${id}/location`,
  GUESTHOUSE_POST: id => `/guesthouses/${id}/posts`,
  GUESTHOUSE_REVIEW: '/guesthouses/reviews',
  GUESTHOUSE_SEARCH: '/guesthouses/search',
  GUESTHOUSES: '/guesthouses',
  POPULAR_GUESTHOUSES: '/guesthouses/popular',
  LOGIN: '/login',
  MAP: '/map',
  MEET_DETAIL: partyId => `/contents/${partyId}`,
  POPULAR_CONTENTS: '/contents/popular',
  MY: '/my',
  NOTIFICATIONS: '/my/notifications',
  NOTIFICATION_SETTINGS: '/my/notifications/settings',
  REGISTER: '/register',
  SETTINGS: '/settings',
  TERMS: '/terms',
  ROOM_DETAIL: roomId => `/rooms/${roomId}`,
};

export const WEB_STATIC_ROUTE_BY_SCREEN = {
  AgreeDetail: '/register/agree/detail',
  ApplicantForm: '/employ/apply',
  ApplySuccess: '/employ/apply/success',
  CouponSelect: '/guesthouse-payment/coupons',
  EmailCertificate: '/register/email',
  FindIntro: '/find',
  FindPassword: '/find/password',
  GuesthouseCancelConfirm: '/my/reservations/guesthouses/cancel',
  GuesthouseCancelledReceipt: '/my/reservations/guesthouses/cancelled',
  GuesthouseCancelSuccess: '/my/reservations/guesthouses/cancel/success',
  GuesthouseCheckInGuide: '/my/reservations/guesthouses/check-in',
  GuesthousePayment: '/guesthouse-payment',
  GuesthousePaymentReceipt: '/my/reservations/guesthouses/receipt',
  GuesthousePaymentSuccess: '/guesthouse-payment/success',
  GuesthouseReservationEntry: '/guesthouse-reservation/select',
  GuesthouseReservation: '/guesthouse-reservation',
  Login: WEB_ROUTES.LOGIN,
  MeetCancelConfirm: '/my/reservations/contents/cancel',
  MeetCancelledReceipt: '/my/reservations/contents/cancelled',
  MeetCancelSuccess: '/my/reservations/contents/cancel/success',
  MeetPayment: '/contents-payment',
  MeetPaymentReceipt: '/my/reservations/contents/receipt',
  MeetPaymentSuccess: '/contents-payment/success',
  MeetReservation: '/contents-reservation',
  MyApplicantList: '/my/applications',
  MyCommunityCommentList: '/my/community/comments',
  MyCommunityPostList: '/my/community/posts',
  MyCouponList: '/my/coupons',
  MyCouponRegister: '/my/coupons/register',
  MyLikeRecruitList: '/my/liked-recruits',
  MyPoint: '/my/points',
  MyResumeList: '/my/resumes',
  PhoneCertificate: '/register/phone',
  PopularEmployList: '/employ/popular',
  PopularGuesthouseList: WEB_ROUTES.POPULAR_GUESTHOUSES,
  PopularMeetList: WEB_ROUTES.POPULAR_CONTENTS,
  ProfileUpdate: '/my/profile/resume',
  RecentGuesthouseList: '/guesthouses/recent',
  RegisterAgree: '/register/agree',
  RegisterIntro: WEB_ROUTES.REGISTER,
  Result: '/register/result',
  ResumeDetail: '/my/resumes/detail',
  Setting: WEB_ROUTES.SETTINGS,
  Terms: WEB_ROUTES.TERMS,
  TemporaryEventBanner: '/events/coupon',
  UserEditInfo: '/my/edit-info',
  UserEditProfile: '/my/edit-profile',
  UserFavorite: '/my/favorites',
  UserFavoriteGuesthouse: '/my/favorites/guesthouses',
  UserFavoriteMeet: '/my/favorites/contents',
  UserGuesthouseReview: '/my/reviews/guesthouses',
  UserGuesthouseReviewForm: '/my/reviews/guesthouses/write',
  UserMeetReservationCancelled: '/my/reservations/contents/cancelled-list',
  UserMeetReservationCheck: '/my/reservations/contents',
  UserRegisterProfile: '/register/profile',
  UserReservationCheck: '/my/reservations/guesthouses',
  VerifyPhone: '/find/phone',
};

export const WEB_SCREEN_BY_STATIC_PATH = Object.entries(
  WEB_STATIC_ROUTE_BY_SCREEN,
).reduce((acc, [screen, path]) => {
  acc[path] = screen;
  return acc;
}, {});
