export const MOCK_MEETS = [
  {
    id: 1,
    placeName: '제주 하루 게스트하우스',
    title: '밤바다 감성 토크 모임',
    thumbnail: require('@assets/images/exphoto.jpeg'),
    address: '제주시 애월읍 곽지리 112',
    price: 30000,
    joined: 6,
    capacity: 10,
    startAt: '2025-07-27T21:00:00',
  },
  {
    id: 2,
    placeName: '서울 홍대 플레이스',
    title: '외국인 교류 파티',
    thumbnail: require('@assets/images/exphoto.jpeg'),
    address: '서울 마포구 와우산로29길 24',
    price: 50000,
    joined: 10,
    capacity: 15,
    startAt: '2025-07-28T19:30:00',
  },
  {
    id: 3,
    placeName: '부산 더뷰 게스트하우스',
    title: '해운대 포차 번개 모임',
    thumbnail: require('@assets/images/exphoto.jpeg'),
    address: '부산 해운대구 구남로 12',
    price: 40000,
    joined: 4,
    capacity: 8,
    startAt: '2025-07-29T20:00:00',
  },
  {
    id: 4,
    placeName: '강릉 소나무집',
    title: '다같이 순두부 먹으러 가요',
    thumbnail: require('@assets/images/exphoto.jpeg'),
    address: '강릉시 초당순두부길 3',
    price: 20000,
    joined: 5,
    capacity: 6,
    startAt: '2025-07-27T11:30:00',
  },
  {
    id: 5,
    placeName: '여수 밤바다 하우스',
    title: '여수 낭만 버스킹 투어',
    thumbnail: require('@assets/images/exphoto.jpeg'),
    address: '여수시 이순신광장로 10',
    price: 35000,
    joined: 8,
    capacity: 12,
    startAt: '2025-07-30T19:00:00',
  },
  {
    id: 6,
    placeName: '속초 힐링쉼터',
    title: '게스트와 함께하는 바베큐 파티',
    thumbnail: require('@assets/images/exphoto.jpeg'),
    address: '속초시 해오름로 88',
    price: 45000,
    joined: 7,
    capacity: 10,
    startAt: '2025-07-31T18:00:00',
  },
  {
    id: 7,
    placeName: '경주 역사 스테이',
    title: '야경 산책 + 첨성대 야시장',
    thumbnail: require('@assets/images/exphoto.jpeg'),
    address: '경주시 첨성로 5',
    price: 25000,
    joined: 3,
    capacity: 6,
    startAt: '2025-07-27T20:30:00',
  },
  {
    id: 8,
    placeName: '전주 한옥게하 소담',
    title: '한옥마을 한복 체험',
    thumbnail: require('@assets/images/exphoto.jpeg'),
    address: '전주시 완산구 태조로 12',
    price: 20000,
    joined: 2,
    capacity: 5,
    startAt: '2025-07-28T14:00:00',
  },
  {
    id: 9,
    placeName: '제주 숲속 쉼터',
    title: '제주 숲 트레킹 모임',
    thumbnail: require('@assets/images/exphoto.jpeg'),
    address: '서귀포시 남원읍 한남로 7',
    price: 30000,
    joined: 9,
    capacity: 10,
    startAt: '2025-07-27T08:00:00',
  },
  {
    id: 10,
    placeName: '부산 청춘게하',
    title: '청춘노래방 같이 가요',
    thumbnail: require('@assets/images/exphoto.jpeg'),
    address: '부산 수영구 민락로 34',
    price: 28000,
    joined: 6,
    capacity: 8,
    startAt: '2025-07-29T22:00:00',
  },
];
