
export const PAYMENT_TYPE = {
  CARD: 'CARD',
  VIRTUAL_ACCOUNT: 'VIRTUAL_ACCOUNT',
  EASY_PAY: 'EASY_PAY',
  MOBILE_PHONE: 'MOBILE_PHONE',
  BANK_TRANSFER: 'BANK_TRANSFER',
  CULTURE_GIFT_CERT: 'CULTURE_GIFT_CERT',
  BOOK_GIFT_CERT: 'BOOK_GIFT_CERT',
  GAME_GIFT_CERT: 'GAME_GIFT_CERT',
  UNKNOWN: 'UNKNOWN',
};

export const PAYMENT_TYPE_LABEL = {
  [PAYMENT_TYPE.CARD]: '카드',
  [PAYMENT_TYPE.VIRTUAL_ACCOUNT]: '가상계좌',
  [PAYMENT_TYPE.EASY_PAY]: '간편결제',
  [PAYMENT_TYPE.MOBILE_PHONE]: '휴대폰',
  [PAYMENT_TYPE.BANK_TRANSFER]: '계좌이체',
  [PAYMENT_TYPE.CULTURE_GIFT_CERT]: '문화상품권',
  [PAYMENT_TYPE.BOOK_GIFT_CERT]: '도서문화상품권',
  [PAYMENT_TYPE.GAME_GIFT_CERT]: '게임문화상품권',
  [PAYMENT_TYPE.UNKNOWN]: '알 수 없음',
};