
install! 'cocoapods', :disable_input_output_paths => true

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# Firebase static framework 설정 (빌드 오류 방지용)
$RNFirebaseAsStaticFramework = true

platform :ios, '15.1'


prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end


target 'trioFrontendApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Firebase modular headers
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true
  pod 'FirebaseInstallations', :modular_headers => true
  pod 'FirebaseABTesting', :modular_headers => true
  pod 'FirebaseRemoteConfig', :modular_headers => true
  pod 'FirebaseSharedSwift', :modular_headers => true
  pod 'GoogleDataTransport', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'nanopb', :modular_headers => true

  post_install do |installer|
    # ① 기존 React Native post_install 호출
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # ───────────────────────────────────────────────────────────────────
    # ② Pods 프로젝트 내부 모든 타겟에 대해 코드 서명 비활성화
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # 이 세 줄이 반드시 있어야 합니다.
        config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
        config.build_settings['CODE_SIGNING_ALLOWED']  = 'NO'
        config.build_settings['CODE_SIGN_IDENTITY']    = ""
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        # Swift Previews 관련 노트를 해결하고 배포용 빌드(Archive) 안정성을 높임
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-O'
        config.build_settings['GCC_OPTIMIZATION_LEVEL'] = 's'
        # (선택) Bitcode도 끄고 싶다면:
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        # (선택) Swift 표준 라이브러리 임베드 비활성화
        config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
        # (선택) 변경되지 않은 프레임워크 스킵 옵션
        config.build_settings['CP_NO_UNCHANGED_FRAMEWORKS'] = 'YES'
      end
    end

    installer.aggregate_targets.each do |aggregate_target|
      aggregate_target.user_project.native_targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        end
      end
      aggregate_target.user_project.save
    end
  end
end
