export const trendingGuesthouses = [
  {
    id: 1,
    name: '제주 그린하우스',
    image: require('@assets/images/exphoto.jpeg'),
    rating: 4.9,
    price: 42000,
    tags: ['파티', '바다 근처'],
  },
  {
    id: 2,
    name: '제주 돌담스테이',
    image: require('@assets/images/exphoto.jpeg'),
    rating: 4.7,
    price: 38000,
    tags: ['조용한 숙소', '한적함'],
  },
  {
    id: 3,
    name: '세화 힐링게스트하우스',
    image: require('@assets/images/exphoto.jpeg'),
    rating: 4.8,
    price: 35000,
    tags: ['여성전용', '감성숙소'],
  },
];


export const popularGuesthouses = [
  {
    id: 4,
    name: '제주 그리고세화',
    image: require('@assets/images/exphoto.jpeg'),
    rating: 4.2,
    price: 30000,
    tags: ['애견동반', '파티'],
  },
  {
    id: 5,
    name: '제주 블루하우스',
    image: require('@assets/images/exphoto.jpeg'),
    rating: 4.1,
    price: 31000,
    tags: ['조식 제공', '조용한 숙소'],
  },
  {
    id: 6,
    name: '성산 일출 스테이',
    image: require('@assets/images/exphoto.jpeg'),
    rating: 4.3,
    price: 32000,
    tags: ['일출뷰', '혼자 여행'],
  },
  {
    id: 7,
    name: '한림오션 게스트하우스',
    image: require('@assets/images/exphoto.jpeg'),
    rating: 4.0,
    price: 29000,
    tags: ['바다 근처', '주차 가능'],
  },
  {
    id: 8,
    name: '애월노을 스테이',
    image: require('@assets/images/exphoto.jpeg'),
    rating: 4.5,
    price: 34000,
    tags: ['노을뷰', '파티'],
  },
  {
    id: 9,
    name: '제주 한라하우스',
    image: require('@assets/images/exphoto.jpeg'),
    rating: 4.2,
    price: 31000,
    tags: ['산책로 인접', '한라산 근처'],
  },
  {
    id: 10,
    name: '제주 게스트114',
    image: require('@assets/images/exphoto.jpeg'),
    rating: 4.4,
    price: 33000,
    tags: ['파티', '야경 좋음'],
  },
  {
    id: 11,
    name: '함덕힐 게스트하우스',
    image: require('@assets/images/exphoto.jpeg'),
    rating: 4.3,
    price: 35000,
    tags: ['루프탑', '해변 인접'],
  },
  {
    id: 12,
    name: '제주 그라운드',
    image: require('@assets/images/exphoto.jpeg'),
    rating: 4.1,
    price: 30000,
    tags: ['잔디마당', '정원'],
  },
  {
    id: 13,
    name: '제주 동백하우스',
    image: require('@assets/images/exphoto.jpeg'),
    rating: 4.2,
    price: 31000,
    tags: ['감성숙소', '사진 명소'],
  },
];
