default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_PRIVATE_KEY"],
      duration: 1200,
      in_house: false
    )

    # 0. DerivedData 삭제
    sh "rm -rf ~/Library/Developer/Xcode/DerivedData"

    # 1. React Native JS 사전 번들링
    sh <<-SHELL
      cd ../
      yarn react-native bundle \
        --platform ios \
        --dev false \
        --entry-file index.js \
        --bundle-output ios/trioFrontendApp/main.jsbundle \
        --assets-dest ios/trioFrontendApp
    SHELL

    # 2. Xcode 빌드
    build_app(
      workspace: "trioFrontendApp.xcworkspace",
      scheme: "trioFrontendApp",
      clean: false,
      output_directory: ".",
      output_name: "trioFrontendApp.ipa",
      silent: false,
      disable_parallelization: true, # 추가
      export_options: {
        compileBitcode: false,
        method: "app-store",
        provisioningProfiles: {
          "com.haneul.workaway" => "WorkAwayAppStoreProfile"
        }
      }
    )

    # 3. TestFlight 업로드
    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: false
    )
  end
end
