import {StyleSheet} from 'react-native';

import {COLORS} from '@constants/colors';

const styles = StyleSheet.create({
  // 화면 기본 레이아웃
  container: {
    flex: 1,
    backgroundColor: COLORS.grayscale_0,
  },
  headerContainer: {
    backgroundColor: COLORS.grayscale_0,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.grayscale_200,
    zIndex: 2,
  },
  mapContainer: {
    flex: 1,
  },
  map: {
    flex: 1,
  },

  // 지도 마커
  markerWrap: {
    padding: 8,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'flex-end',
    zIndex: 10,
    elevation: 10,
  },
  markerBubbleOverlay: {
    position: 'absolute',
    width: 232,
    alignItems: 'center',
    zIndex: 30,
    elevation: 30,
  },
  markerBubble: {
    backgroundColor: COLORS.grayscale_0,
    borderRadius: 24,
    padding: 8,
    borderWidth: 2,
    borderColor: COLORS.primary_orange,
    shadowColor: COLORS.grayscale_900,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.08,
    shadowRadius: 6,
    zIndex: 31,
    elevation: 31,
    position: 'relative',
  },
  markerBubbleTail: {
    position: 'absolute',
    bottom: -8,
    alignSelf: 'center',
    width: 16,
    height: 16,
    backgroundColor: COLORS.grayscale_0,
    borderRightWidth: 2,
    borderBottomWidth: 2,
    borderColor: COLORS.primary_orange,
    transform: [{rotate: '45deg'}],
  },
  clusterList: {
    minWidth: 200,
    maxWidth: 200,
    gap: 12,
  },
  clusterListItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  clusterListIcon: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: COLORS.primary_orange,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  clusterListName: {
    flex: 1,
    color: COLORS.grayscale_900,
  },
  clusterListPrice: {
    color: COLORS.grayscale_900,
    flexShrink: 0,
  },
  singleMarkerContent: {
    minWidth: 100,
    maxWidth: 120,
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  singleMarkerName: {
    color: COLORS.grayscale_900,
  },
  singleMarkerPrice: {
    color: COLORS.grayscale_900,
    fontSize: 14,
  },
  singleMarkerTextWrap: {
    gap: 2,
  },
  markerContainer: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
    elevation: 1,
  },
  homeMarker: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.primary_orange,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: COLORS.grayscale_0,
  },
  selectedMarkerDot: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: COLORS.primary_orange,
    borderWidth: 2,
    borderColor: COLORS.grayscale_0,
  },
  markerCountBadge: {
    position: 'absolute',
    top: -2,
    right: -2,
    minWidth: 18,
    height: 18,
    paddingHorizontal: 4,
    borderRadius: 9,
    backgroundColor: COLORS.grayscale_900,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: COLORS.grayscale_0,
  },
  markerCountText: {
    color: COLORS.grayscale_0,
    fontSize: 10,
  },

  // 지도 위 고정 버튼
  researchButtonContainer: {
    position: 'absolute',
    top: 20,
    left: 0,
    right: 0,
    alignItems: 'center',
  },
  researchButton: {
    backgroundColor: COLORS.grayscale_0,
    borderRadius: 20,
    paddingHorizontal: 18,
    paddingVertical: 10,
    shadowColor: COLORS.grayscale_900,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  researchButtonText: {
    color: COLORS.grayscale_900,
  },
  bottomControlRow: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 24,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    zIndex: 20,
  },
  cardTopControlRow: {
    position: 'absolute',
    left: 0,
    top: -48,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    zIndex: 22,
  },
  currentLocationButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.grayscale_0,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: COLORS.grayscale_900,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  listToggleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.grayscale_0,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    shadowColor: COLORS.grayscale_900,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  listToggleButtonText: {
    marginLeft: 8,
    color: COLORS.grayscale_900,
  },

  // 로딩 / 빈 상태
  loadingOverlay: {
    position: 'absolute',
    top: 72,
    right: 16,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.grayscale_0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyCard: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 64,
    backgroundColor: COLORS.grayscale_0,
    borderRadius: 24,
    paddingHorizontal: 20,
    paddingVertical: 18,
    shadowColor: COLORS.grayscale_900,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 4,
  },
  emptyTitle: {
    color: COLORS.grayscale_800,
    textAlign: 'center',
  },

  // 하단 상세 카드
  cardArea: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 12,
  },
  cardSwitchContainer: {
    position: 'absolute',
    right: 8,
    top: -36,
    flexDirection: 'row',
    gap: 8,
    zIndex: 21,
  },
  cardSwitchButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: COLORS.grayscale_0,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: COLORS.grayscale_900,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 2,
  },
  detailCard: {
    backgroundColor: COLORS.grayscale_0,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 18,
    shadowColor: COLORS.grayscale_900,
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 4,
  },
  detailHeader: {
    flex: 1,
    gap: 4,
  },
  detailWrap: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  detailTitle: {
    flex: 1,
    minWidth: 0,
    color: COLORS.grayscale_900,
  },
  detailAddress: {
    flex: 1,
    minWidth: 0,
    color: COLORS.grayscale_500,
  },
  favoriteButton: {
    flexShrink: 0,
  },
  detailPrice: {
    flexShrink: 0,
    color: COLORS.grayscale_900,
  },
  tagRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
    marginBottom: 12,
  },
  tagChip: {
    backgroundColor: COLORS.grayscale_100,
    borderRadius: 100,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  tagText: {
    color: COLORS.primary_blue,
  },
  imageRow: {
    flexDirection: 'row',
  },
  detailImage: {
    width: 108,
    height: 108,
    borderRadius: 16,
    backgroundColor: COLORS.grayscale_200,
  },
  detailImagePlaceholder: {
    backgroundColor: COLORS.grayscale_200,
  },
});

export default styles;
